### ISSUE TITLE
Not able to POST through the API

### ISSUE THREAD

**Issue by lamynes** [atharvadeosthale/rest-api-mysql-article#1]
I am using your example exactly as it is and I can't seem to Post/Insert data.

Example app listening at http://localhost:3000

Error while creating programming language Unknown column 'undefined' in 'field list'
Unknown column 'undefined' in 'field list' Error: Unknown column 'undefined' in 'field list'
    at PromiseConnection.execute (C:\Users\lamyn\OneDrive\Documents\nodeApp\programming-languages-api\node_modules\mysql2\promise.js:111:22)
    at Object.query (C:\Users\lamyn\OneDrive\Documents\nodeApp\programming-languages-api\services\db.js:6:40)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.create (C:\Users\lamyn\OneDrive\Documents\nodeApp\programming-languages-api\services\programmingLanguages.js:21:18)
    at async C:\Users\lamyn\OneDrive\Documents\nodeApp\programming-languages-api\routes\programmingLanguages.js:18:14

**Comment by ReactNativeSandeep** [comment]
![POST_Raw_Data](https://user-images.githubusercontent.com/64374265/178555700-5fd6d815-6082-405f-8453-58081af83bc8.PNG)
@lamynes you have to **POST** the Data in the **Row** in Postman Like in the Attached Screenshot. it will Resolve your issue.
